"""add product image brand rating

Revision ID: 21b75a11ad7a
Revises: c1762e20a553
Create Date: 2026-07-22 15:20:18.203163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21b75a11ad7a'
down_revision: Union[str, Sequence[str], None] = 'c1762e20a553'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('products', sa.Column('brand', sa.String(), nullable=True))
    op.add_column('products', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('discount_percentage', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'discount_percentage')
    op.drop_column('products', 'rating')
    op.drop_column('products', 'brand')
    op.drop_column('products', 'image_url')
    # ### end Alembic commands ###
